# -*- mode: python -*-

Import('env')

# S-Lang
env.ParseConfig('pkg-config --cflags --libs slang')

# v8
env.Prepend(CCFLAGS = '-g -Wall -Werror -pedantic')
env.Append(CPPPATH = Dir('../deps/v8/src'))
env.Append(LIBS = File('../deps/v8/libv8.a'))
if env['PLATFORM'] == 'darwin':
    env.Append(CCFLAGS = '-fvisibility=hidden -m64')

env.Program(target='noble', source=[
        'fs.cc',
        'global.cc',
        'system.cc',
        'term.cc',
        'noble.cc',
        ])
