# -*- mode: python -*-

Import('env')

# ncurses
env.ParseConfig('ncurses5-config --cflags --libs')

# v8
env.Prepend(CCFLAGS = '-g -Wall')
if env['PLATFORM'] == 'darwin':
    env.Prepend(CCFLAGS = '-fvisibility=hidden')
env.Append(CPPPATH = Dir('../deps/v8/src'))
env.Append(LIBS = File('../deps/v8/libv8.a'))

env.Program(target='noble', source=['noble.cc'])
